// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Orneholm.ApplicationInsights.Web;
using Orneholm.ApplicationInsights.Web.Models;

namespace Orneholm.ApplicationInsights.Web
{
    public static partial class AgeCalculatorExtensions
    {
        /// <param name='operations'>
        /// Reference to the Orneholm.ApplicationInsights.Web.IAgeCalculator.
        /// </param>
        /// <param name='dateOfBirth'>
        /// Required.
        /// </param>
        public static Age GetByDateofbirth(this IAgeCalculator operations, DateTimeOffset dateOfBirth)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IAgeCalculator)s).GetByDateofbirthAsync(dateOfBirth);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Orneholm.ApplicationInsights.Web.IAgeCalculator.
        /// </param>
        /// <param name='dateOfBirth'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Age> GetByDateofbirthAsync(this IAgeCalculator operations, DateTimeOffset dateOfBirth, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Orneholm.ApplicationInsights.Web.Models.Age> result = await operations.GetByDateofbirthWithOperationResponseAsync(dateOfBirth, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
