// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Orneholm.ApplicationInsights.Web.Models;

namespace Orneholm.ApplicationInsights.Web
{
    public partial interface IAgeCalculator
    {
        /// <param name='dateOfBirth'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Age>> GetByDateofbirthWithOperationResponseAsync(DateTimeOffset dateOfBirth, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
