// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using Orneholm.ApplicationInsights.Web;

namespace Orneholm.ApplicationInsights.Web
{
    public partial class PoAiDemoApi : ServiceClient<PoAiDemoApi>, IPoAiDemoApi
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IAgeCalculator _ageCalculator;
        
        public virtual IAgeCalculator AgeCalculator
        {
            get { return this._ageCalculator; }
        }
        
        /// <summary>
        /// Initializes a new instance of the PoAiDemoApi class.
        /// </summary>
        public PoAiDemoApi()
            : base()
        {
            this._ageCalculator = new AgeCalculator(this);
            this._baseUri = new Uri("https://microsoft-apiapp277ddd1d2bce4487bc0a0efbd4013d5d.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the PoAiDemoApi class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public PoAiDemoApi(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._ageCalculator = new AgeCalculator(this);
            this._baseUri = new Uri("https://microsoft-apiapp277ddd1d2bce4487bc0a0efbd4013d5d.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the PoAiDemoApi class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public PoAiDemoApi(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._ageCalculator = new AgeCalculator(this);
            this._baseUri = new Uri("https://microsoft-apiapp277ddd1d2bce4487bc0a0efbd4013d5d.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the PoAiDemoApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public PoAiDemoApi(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the PoAiDemoApi class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public PoAiDemoApi(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the PoAiDemoApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public PoAiDemoApi(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
